# https://developer.twitter.com/en/portal/apps/new

name = "@earlgrayyyy!!!!"

[client]
api_key = "api_keyyyy!!!!"
api_secret_key = "api_secret_keyyyy!!!!"
access_token = "access_tokennnn!!!!"
access_token_secret = "amazing_mightyyyy!!!!"