# Example of Config.toml
# It is located on `$HOME/.config/rtwi`
# You can generate Twitter api key on https://developer.twitter.com/en/portal/apps/new

name = "@earlgrayyyy!!!!"

[twitter_api_info]
api_key = "api_keyyyy!!!!"
api_secret_key = "api_secret_keyyyy!!!!"
access_token = "access_tokennnn!!!!"
access_token_secret = "amazing_mightyyyy!!!!"